In [12]:
import torch
print(torch.__version__)

2.11.0


In [13]:
x = torch.tensor(3.0, requires_grad = True)
x

tensor(3., requires_grad=True)

In [29]:
y  = x**2
y

tensor(9., grad_fn=<PowBackward0>)

In [30]:
y.backward()

In [31]:
x.grad

tensor(30.)

In [32]:
import math

In [40]:
def dz_dx(x):
    return 2*x*math.cos(x**2)

In [41]:
dz_dx(4)

-7.661275842587077

In [42]:
x = torch.tensor(4.0, requires_grad = True)

In [44]:
y = x**2

In [45]:
z = torch.sin(y)

In [46]:
x

tensor(4., requires_grad=True)

In [47]:
y

tensor(16., grad_fn=<PowBackward0>)

In [48]:
z

tensor(-0.2879, grad_fn=<SinBackward0>)

In [49]:
z.backward()

In [51]:
x.grad

tensor(-7.6613)

In [54]:
y.grad # only leaf tensor is allowed to compute the grad.

/var/folders/17/35md0zr16hvdjvkw_fln7jxw0000gn/T/ipykernel_29090/3384622175.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/core/TensorBody.h:499.)
  y.grad # only leaf tensor is allowed to compute the grad.


## Caluclate Loss: Binary Cross Entropy

$$ \mathcal{L} = - [y \log(p) + (1 - y) \log(1 - p)] $$


In [56]:
x = torch.tensor(6.7) # input
y = torch.tensor(0.0) #not converted / True label binary

w = torch.tensor(1.0) # weight
b = torch.tensor(0.0) # bias

In [89]:
def binary_cross_entropy_loss(prediction, target):
    epsilon = 1e-8 # to prevent log(0)
    prediction = torch.clamp(prediction, epsilon, 1-epsilon)
    return -(target * torch.log(prediction)+(1-target) * torch.log(1-prediction))

In [90]:
# Forward pass
z = w * x + b

y_pred = torch.sigmoid(z) # predicted probability

# loss
loss = binary_cross_entropy_loss(y_pred, y)

In [91]:
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [92]:
# Derivatives:
# 1. dL/d(y_pred): Loss with respect to the prediction (y_pred)
dloss_dy_pred = (y_pred - y)/(y_pred*(1-y_pred))

# 2. dy_pred/dz: Prediction (y_pred) with respect to z (sigmoid derivative)
dy_pred_dz = y_pred * (1 - y_pred)

# 3. dz/dw and dz/db: z with respect to w and b
dz_dw = x  # dz/dw = x
dz_db = 1  # dz/db = 1 (bias contributes directly to z)

dL_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dL_db = dloss_dy_pred * dy_pred_dz * dz_db

In [93]:
print(f"Manual Gradient of loss w.r.t weight (dw): {dL_dw}")
print(f"Manual Gradient of loss w.r.t bias (db): {dL_db}")

Manual Gradient of loss w.r.t weight (dw): 6.691762447357178
Manual Gradient of loss w.r.t bias (db): 0.998770534992218


In [94]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [95]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [96]:
w

tensor(1., requires_grad=True)

In [97]:
b

tensor(0., requires_grad=True)

In [98]:
z = w*x + b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [99]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [100]:
loss = binary_cross_entropy_loss(y_pred,y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [101]:
loss.backward()

In [103]:
print(w.grad)
print(b.grad)

tensor(6.6918)
tensor(0.9988)


In [105]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad = True)
x

tensor([1., 2., 3.], requires_grad=True)

In [136]:
y = (x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [137]:
y.backward()

In [138]:
x.grad

tensor([1.3333, 2.6667, 4.0000])

In [139]:
# Clearing Grad:
x.grad.zero_()

tensor([0., 0., 0.])

In [140]:
# option 1 - requires_grad_(False)
# option 2 - detach()
# option 3 - torch.no_grad()

In [141]:
# disable gradient tracking
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [143]:
x.requires_grad_(False)

tensor(2.)

In [144]:
y = x**2

In [145]:
y

tensor(4.)

In [148]:
y.backward() # Not allowed as gradient has been disabled

In [149]:
# disable gradient tracking
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [150]:
x.detach()

tensor(2.)

In [152]:
y.backward() # Not allowed as gradient has been disabled

In [153]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [157]:
with torch.no_grad():
    y = x**2


In [158]:
y

tensor(4.)