In [12]:
import torch
print(torch.__version__)

2.11.0


In [13]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not availbale")

GPU is not availbale


# Creating a Tensors

In [83]:
# Using empty
x = torch.empty(20,100)
x

tensor([[0.0000e+00, 0.0000e+00, 6.1657e-44,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        ...,
        [2.3799e-19, 1.4013e-45, 2.8418e-19,  ..., 1.4013e-45, 2.6944e-19,
         1.4013e-45],
        [2.6939e-19, 1.4013e-45, 2.6945e-19,  ..., 1.4013e-45, 2.6962e-19,
         1.4013e-45],
        [2.6962e-19, 1.4013e-45, 2.6967e-19,  ..., 1.4013e-45, 2.6970e-19,
         1.4013e-45]])

In [19]:
#check type
type(x)

torch.Tensor

In [85]:
# Using Zeros
torch.zeros(3,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [23]:
# Using Ones
torch.ones(3,6)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [28]:
# Using rand
torch.rand(2,4)

tensor([[0.3127, 0.6791, 0.5988, 0.8428],
        [0.7916, 0.6805, 0.7554, 0.0424]])

In [41]:
# Use of seed
x = torch.rand(2,4)
x

tensor([[0.8045, 0.6357, 0.5896, 0.6933],
        [0.8782, 0.5407, 0.1400, 0.9613]])

In [53]:
# Use of manual_seed
torch.manual_seed(41)
y = torch.rand(2,4)
y

tensor([[0.2364, 0.2266, 0.8005, 0.1692],
        [0.2650, 0.7720, 0.1282, 0.7452]])

In [56]:
# using tensors
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [114]:
# Other ways to create tensors:

# using arrange:
print("tensor using arange:->>> : ", torch.arange(0,11,2))
print("tensor using arange:->>> : ", torch.arange(0,11,3))

# using linspace:
print("tensor using Linear Space:->>> : ", torch.linspace(0,10,5))

# using eye:
print("tensor using arange:->>> : ", torch.eye(4))
# using full:
print("tensor using arange:->>> : ", torch.full((3,3),5))

tensor using arange:->>> :  tensor([ 0,  2,  4,  6,  8, 10])
tensor using arange:->>> :  tensor([0, 3, 6, 9])
tensor using Linear Space:->>> :  tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
tensor using arange:->>> :  tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor using arange:->>> :  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [127]:
torch.manual_seed(43)
x = torch.rand(2,4)
x

tensor([[0.4540, 0.1965, 0.9210, 0.3462],
        [0.1481, 0.0858, 0.5909, 0.0659]])

In [128]:
x.shape

torch.Size([2, 4])

In [129]:
torch.empty_like(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [130]:
torch.zeros_like(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [131]:
torch.ones_like(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [132]:
torch.rand_like(x)

tensor([[0.7476, 0.6253, 0.9392, 0.1338],
        [0.5191, 0.5335, 0.5375, 0.7058]])

# Tensor Data Types

In [139]:
a = torch.tensor([[1,2,3],[4,5,6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [140]:
a.dtype

torch.int64

In [142]:
b = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.int32)
b

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [143]:
b = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float64)
b

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [146]:
# Using to()
z = torch.tensor([1,2,3])
z

tensor([1, 2, 3])

In [147]:
z.to(dtype=torch.float32)

tensor([1., 2., 3.])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# Mathematical Operations:

## 1. Scalar operation

In [149]:
x = torch.rand(2,3)
x

tensor([[0.3241, 0.8892, 0.1318],
        [0.8375, 0.5625, 0.4138]])

In [157]:
# Addition

print("Addition in tensor: ", x+2)

#Subtraction
print("Subtraction in tensor: ", x-1)

# Multiplication
print("Multiplication in tensor: ", x*1000)
# Division
print("Division in tensor: ", x*1000 / 10)
# Int devision

y = torch.tensor([[10,15,20],[12,16,18]])
print("Integer Division in tensor: ", y // 5)
                 
# Modulus

print("Moldulus in tensor: ", y%4)

# Power
print("Power in tensor: ", y**2)

Addition in tensor:  tensor([[2.3241, 2.8892, 2.1318],
        [2.8375, 2.5625, 2.4138]])
Subtraction in tensor:  tensor([[-0.6759, -0.1108, -0.8682],
        [-0.1625, -0.4375, -0.5862]])
Multiplication in tensor:  tensor([[324.0624, 889.2430, 131.8074],
        [837.4526, 562.5421, 413.8319]])
Division in tensor:  tensor([[32.4062, 88.9243, 13.1807],
        [83.7453, 56.2542, 41.3832]])
Integer Division in tensor:  tensor([[2, 3, 4],
        [2, 3, 3]])
Moldulus in tensor:  tensor([[2, 3, 0],
        [0, 0, 2]])
Power in tensor:  tensor([[100, 225, 400],
        [144, 256, 324]])


## 2. Element wise operation

In [168]:
a = torch.rand(2,3)
b = torch.full((2,3),2)
print(a)
print(b)

tensor([[0.3490, 0.0966, 0.1141],
        [0.8013, 0.4495, 0.7612]])
tensor([[2, 2, 2],
        [2, 2, 2]])


In [180]:
# Add
a+b

# Subtract
a - b

# Multiply

a*b

# Division

a/b

# Power

a**b

# Mod

a%b

tensor([[0.3490, 0.0966, 0.1141],
        [0.8013, 0.4495, 0.7612]])

In [182]:
m = torch.tensor([3,-2,5,-8])
m

tensor([ 3, -2,  5, -8])

In [184]:
# Absolute
torch.abs(m)

tensor([3, 2, 5, 8])

In [186]:
# Negative
torch.neg(m)

tensor([-3,  2, -5,  8])

In [188]:
n = torch.tensor([1.2, 4.3, 6.3, 8.2])
n

tensor([1.2000, 4.3000, 6.3000, 8.2000])

In [189]:
torch.round(n)

tensor([1., 4., 6., 8.])

In [190]:
# Ceil
torch.ceil(n)

tensor([2., 5., 7., 9.])

In [191]:
# Floor
torch.floor(n)

tensor([1., 4., 6., 8.])

In [192]:
# Max
torch.max(n)

tensor(8.2000)

In [193]:
# Min
torch.min(n)

tensor(1.2000)

In [198]:
# Clamp
torch.clamp(n, min=1, max=9)

tensor([1.2000, 4.3000, 6.3000, 8.2000])

## 3. Reduction operation

In [209]:
p = torch.randint(size=(2,3), low=0, high=10, dtype =torch.float32)
p

tensor([[0., 9., 0.],
        [7., 5., 9.]])

In [213]:
# sum along columns
torch.sum(p, dim=0)

# sum along row
torch.sum(p, dim=1)

tensor([ 9., 21.])

In [218]:
# Mean along columns
torch.mean(p, dim=0)

# Mean along row
torch.mean(p, dim=1)

tensor([3., 7.])

In [220]:
# Median along columns
torch.median(p, dim=0)

# Median along rows
torch.median(p, dim=1)

torch.return_types.median(
values=tensor([0., 7.]),
indices=tensor([2, 0]))

In [222]:
# Product
torch.prod(p)

tensor(0.)

In [223]:
# Standard deviation
torch.std(p)

tensor(4.1473)

In [226]:
# Variance
torch.var(p)

tensor(17.2000)

In [228]:
# Argmax: Return index of the highest value
torch.argmax(p) 

tensor(1)

In [229]:
# argmin
torch.argmin(p)

tensor(0)

## 4. Matrix operation

In [252]:
m = torch.randint(size = (3,2), low = 0, high = 10)
n = torch.randint(size = (2,3), low = 0, high = 10)
print(m)
print(n)

tensor([[4, 7],
        [8, 5],
        [2, 5]])
tensor([[9, 4, 3],
        [5, 8, 7]])


In [239]:
# Matrix multiplication
torch.matmul(m,n)

tensor([[27, 29, 36],
        [41, 43, 52],
        [18, 17, 18]])

In [240]:
# Matrix Dot product
vector1 = torch.tensor([1,2,3])
vector2 = torch.tensor([4,5,6])

In [238]:
torch.dot(vector1, vector2)

tensor(32)

In [241]:
# transpose
torch.transpose(m, 0,1)

tensor([[3, 5, 3],
        [5, 7, 2]])

In [243]:
h = torch.randint(size=(3,3), low = 1, high=10, dtype = torch.float32)
h

tensor([[6., 7., 4.],
        [8., 9., 8.],
        [6., 1., 4.]])

In [245]:
# Determinant
torch.det(h)

tensor(96.0000)

In [246]:
# inverse
torch.inverse(h)

tensor([[ 0.2917, -0.2500,  0.2083],
        [ 0.1667, -0.0000, -0.1667],
        [-0.4792,  0.3750, -0.0208]])

## 5. Comparision operation

In [256]:
u = torch.randint(size = (3,2), low = 0, high = 10)
v = torch.randint(size = (3,2), low = 0, high = 10)
print(u)
print(v)

tensor([[8, 8],
        [0, 2],
        [3, 2]])
tensor([[9, 9],
        [0, 0],
        [3, 5]])


In [266]:
#Greater than
u > v

#Less than
u < v

# Equal to
u == v

# Not Equal to
u != v

#Greater than and equal to
u >= v

#Less than and equal to 
u <= v

tensor([[ True,  True],
        [ True, False],
        [ True,  True]])

## 6. Special Functions

In [267]:
k = torch.randint(size = (2,3), low = 0, high = 10, dtype = torch.float32)
k

tensor([[0., 3., 0.],
        [0., 8., 7.]])

In [268]:
# log

torch.log(k)

tensor([[  -inf, 1.0986,   -inf],
        [  -inf, 2.0794, 1.9459]])

In [269]:
#exponential
torch.exp(k)

tensor([[1.0000e+00, 2.0086e+01, 1.0000e+00],
        [1.0000e+00, 2.9810e+03, 1.0966e+03]])

In [270]:
#Square root:
torch.sqrt(k)

tensor([[0.0000, 1.7321, 0.0000],
        [0.0000, 2.8284, 2.6458]])

In [271]:
#sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.9526, 0.5000],
        [0.5000, 0.9997, 0.9991]])

In [272]:
#Softmax
torch.softmax(k, dim=0)

tensor([[5.0000e-01, 6.6929e-03, 9.1105e-04],
        [5.0000e-01, 9.9331e-01, 9.9909e-01]])

In [273]:
#relu
torch.relu(k)

tensor([[0., 3., 0.],
        [0., 8., 7.]])

# Inspace operation

In [275]:
c = torch.rand(2,3)
d = torch.rand(2,3)
print(c)
print(d)

tensor([[0.4681, 0.9621, 0.4443],
        [0.5900, 0.7766, 0.7444]])
tensor([[0.5222, 0.8894, 0.1678],
        [0.6473, 0.0379, 0.8159]])


In [276]:
c.add_(d)

tensor([[0.9902, 1.8515, 0.6121],
        [1.2373, 0.8145, 1.5602]])

In [277]:
c

tensor([[0.9902, 1.8515, 0.6121],
        [1.2373, 0.8145, 1.5602]])

In [278]:
d

tensor([[0.5222, 0.8894, 0.1678],
        [0.6473, 0.0379, 0.8159]])

In [281]:
torch.relu(c)

tensor([[0.9902, 1.8515, 0.6121],
        [1.2373, 0.8145, 1.5602]])

In [282]:
c.relu_()

tensor([[0.9902, 1.8515, 0.6121],
        [1.2373, 0.8145, 1.5602]])

In [283]:
c

tensor([[0.9902, 1.8515, 0.6121],
        [1.2373, 0.8145, 1.5602]])

# Copying a Tensor

In [285]:
f = torch.rand(2,3)
f

tensor([[0.3796, 0.3385, 0.2939],
        [0.8167, 0.1573, 0.6731]])

In [286]:
a = f

In [287]:
a

tensor([[0.3796, 0.3385, 0.2939],
        [0.8167, 0.1573, 0.6731]])

In [288]:
id(a)

4845108944

In [289]:
id(f)

4845108944

In [290]:
b = f.clone()

In [291]:
b

tensor([[0.3796, 0.3385, 0.2939],
        [0.8167, 0.1573, 0.6731]])

In [292]:
id(b)

4845598384

In [294]:
b[0][0] = 10

In [295]:
b

tensor([[10.0000,  0.3385,  0.2939],
        [ 0.8167,  0.1573,  0.6731]])

In [296]:
id(b)

4845598384