In [12]:
import torch
print(torch.__version__)

2.11.0


In [13]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not availbale")

GPU is not availbale


# Creating a Tensors

In [83]:
# Using empty
x = torch.empty(20,100)
x

tensor([[0.0000e+00, 0.0000e+00, 6.1657e-44,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        ...,
        [2.3799e-19, 1.4013e-45, 2.8418e-19,  ..., 1.4013e-45, 2.6944e-19,
         1.4013e-45],
        [2.6939e-19, 1.4013e-45, 2.6945e-19,  ..., 1.4013e-45, 2.6962e-19,
         1.4013e-45],
        [2.6962e-19, 1.4013e-45, 2.6967e-19,  ..., 1.4013e-45, 2.6970e-19,
         1.4013e-45]])

In [19]:
#check type
type(x)

torch.Tensor

In [85]:
# Using Zeros
torch.zeros(3,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [23]:
# Using Ones
torch.ones(3,6)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [28]:
# Using rand
torch.rand(2,4)

tensor([[0.3127, 0.6791, 0.5988, 0.8428],
        [0.7916, 0.6805, 0.7554, 0.0424]])

In [41]:
# Use of seed
x = torch.rand(2,4)
x

tensor([[0.8045, 0.6357, 0.5896, 0.6933],
        [0.8782, 0.5407, 0.1400, 0.9613]])

In [53]:
# Use of manual_seed
torch.manual_seed(41)
y = torch.rand(2,4)
y

tensor([[0.2364, 0.2266, 0.8005, 0.1692],
        [0.2650, 0.7720, 0.1282, 0.7452]])

In [56]:
# using tensors
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [114]:
# Other ways to create tensors:

# using arrange:
print("tensor using arange:->>> : ", torch.arange(0,11,2))
print("tensor using arange:->>> : ", torch.arange(0,11,3))

# using linspace:
print("tensor using Linear Space:->>> : ", torch.linspace(0,10,5))

# using eye:
print("tensor using arange:->>> : ", torch.eye(4))
# using full:
print("tensor using arange:->>> : ", torch.full((3,3),5))

tensor using arange:->>> :  tensor([ 0,  2,  4,  6,  8, 10])
tensor using arange:->>> :  tensor([0, 3, 6, 9])
tensor using Linear Space:->>> :  tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
tensor using arange:->>> :  tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor using arange:->>> :  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

# Tensor Data Types

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# Mathematical Operations:

## 1. Scalar operation

## 2. Element wise operation

## 3. Reduction operation

## 4. Matrix operation

## 5. Comparision operation

## 6. Special Functions

# Inspace operation

# Copying a Tensor